# config/cloudinary.yml
development:
  cloud_name: "dsegcukxy"
  api_key: "123837668317786"
  api_secret: "8E7ARHlp1ZK2ObBpB5dNtgDUKJQ"

production:
  cloud_name: "dsegcukxy"
  api_key: "123837668317786"
  api_secret: "8E7ARHlp1ZK2ObBpB5dNtgDUKJQ"